title: ELPS 611: Boards and Community Relations
logo: /assets/scooby_DS.png
description: Course files and content for the Introduction to Data Science Course.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
