title: ELPS 611, Boards and Community Relations
logo: /assets/elps-class-logo.png
description: Course files and content for Spring 2026
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
